### ISSUE TITLE
Join contributte

### ISSUE THREAD

**Issue by f3l1x** [Arachne/EventManager#1]
Hi! 

I've got a crazy idea about merge this package with `contributte/event-dispatcher`. Or maybe some others which can bring more value for all developers. What do you think? Would you mind to join contributte organization and work on repositories together?

Thanks Felix

**Comment by enumag** [comment]
This package has nothing to do with symfony/event-dispatcher. This is a simple integration of Doctrine\Common\EventManager to Nette which I'm using for Doctrine ORM events instead of the overcomplicated Kdyby/Event package.

I did have [arachne/event-dispatcher](https://github.com/DeprecatedPackages/ArachneEventDispatcher) package as well which I already deprecated in favor of contributte/event-dispatcher.

**Comment by enumag** [comment]
The point is this package is not meant to be used instead of contributte/event-dispatcher but rather together with it if you're using kdyby/doctrine. See https://github.com/Kdyby/Doctrine/pull/266 for details.

**Comment by f3l1x** [comment]
Oh, my mistake. Thanks. On the other hand, you´re welcome to join me and some others in contributte. If you´re interesting of moving some of your packages. :)

Just think about it.

**Comment by enumag** [comment]
Maybe in the future. There are 17 packages in Arachne, all of which are active (I already removed the trash) so moving them all would be a pain and I don't feel like moving just some of them - most of them have some relations to the others. Thanks for the offer though.

**Comment by f3l1x** [comment]
Thank you for consideration. ;-)
